apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: training-ai
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: training-ai-basic-auth
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
spec:
  ingressClassName: nginx
  rules:
    - host: training-ai.atorma.fi
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: training-ai
                port:
                  number: 7932
  tls:
    - hosts:
        - training-ai.atorma.fi
      secretName: training-ai-certificate-secret